version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gamezone_web
    ports:
      - "80:80"
    volumes:
      - ./gamezone:/var/www/html   # Volumen local mapeado al contenedor
    networks:
      - app-network
    restart: "always"
    environment:
      APACHE_LOG_DIR: /var/log/apache2

  db:
    image: mariadb
    container_name: gamezone_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gamezone
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql  # Volumen local para datos persistentes
    networks:
      - app-network
    restart: "always"

  adminer:
    image: adminer
    container_name: gamezone_adminer
    ports:
      - "8081:8080"
    networks:
      - app-network
    restart: "always"

networks:
  app-network:
    driver: bridge

volumes:
  db_data:

